### ISSUE TITLE
Built files disappear..

### ISSUE THREAD

**Issue by ijbranch** [FMXExpress/Delphi-Parallel-Build#1]
What a great idea.
D10.4.1, Win 10 64 bit.
Built the App, no issues.
Installed MSBuild, no issues.
Ran the App and loaded a project set, 18 projects.
Selected Build All.
All went through the motions OK, I saw the files appearing in the relevant directory and then they would promptly disappear????
Have I missed some setting??

Suggestion, have it remember the last directory that was selected/used.

Regards,
Ian

**Comment by ijbranch** [comment]
OK.  "Clean after build" switch in settings.
I can see the need to clean up but surely not delete the actual .exe files generated.  :-(

**Comment by FMXExpress** [comment]
In my scenario I prefer they don't stick around so not sure at the moment. Here are the command line options.
http://docwiki.embarcadero.com/RADStudio/Sydney/en/Building_a_Project_Using_an_MSBuild_Command

**Comment by ijbranch** [comment]
Hmmmm.  Interesting.  I built a project from the IDE and was 35000832 bytes.
I built it using DPB and it was 28699648.
My obvious question is, why the difference?
Investigating.

**Comment by ijbranch** [comment]
Reason found.  No Eurekalog post processing.
